[package]
name = "Quick-Newbee"
version = "0.1.0"
description = "Quick is a lightweight app that runs web tools in clean desktop windows."
authors = ["you"]
edition = "2021"


[workspace]
members = [".", "migration"]

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "quick_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", 'image-ico'] }
tauri-plugin-opener = "2"

# 本地模块
migration = { path = "migration" }


# Tauri 插件
tauri-plugin-single-instance = "2" # 单实例
tauri-plugin-fs = "2"              # 文件系统
tauri-plugin-shell = "2"           # 系统命令
tauri-plugin-notification = "2"    # 通知
tauri-plugin-os = "2"              # 系统
tauri-plugin-http = "2"            # http
tauri-plugin-dialog = "2"          # 对话框
tauri-plugin-log = "2"             # 日志

# 工具库
tokio = { version = "1", features = ["full"] }
log = "0.4"
thiserror = "1.0"
lazy_static = "1.4.0"
parking_lot = "0.12"
url = "2.5.0"
sha2 = "0.10.8"
flexi_logger = "0.28"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
directories = "6"
once_cell = "1.20.3"


# 系统交互
mouse_position = "0.1.3"
enigo = "0.2.1"
active-win-pos-rs = "0.8"

# Web 框架
actix-http = "3"
actix-web = "4"
actix-cors = "0.6"
listenfd = "1"

# 数据库 ORM
sea-orm = { version = "1.1.2", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
] }


# macos
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.24"
core-foundation = "0.9"
core-foundation-sys = "0.8"
objc_id = "0.1"
# tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", branch = "v2" }


# 非移动端插件
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"       # 开机自启
tauri-plugin-global-shortcut = "2" # 全局快捷键
tauri-plugin-updater = "2"         # 自动更新
