// file_path: src/infrastructure/entity/proxies.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "proxies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub title: String,
    pub r#type: String,
    pub host: String,
    pub port: i32,
    pub username: String,
    pub password: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::windows::Entity")]
    Windows,
}

impl Related<super::windows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Windows.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
