// file_path: src/infrastructure/entity/windows.rs
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "windows")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub title: String,
    pub url: String,
    pub icon: String,
    pub sort_order: i32,
    pub proxy_id: i32,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::proxies::Entity",
        from = "Column::ProxyId",
        to = "super::proxies::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Proxies,
}

impl Related<super::proxies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Proxies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
